[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "solyx-energy-api-client"
version = "0.1.1"
license = "MIT"
license-files = ["LICENSE"]
description = "Async API client for Solyx Energy devices"
readme = "README.md"
requires-python = ">=3.14.2"
dependencies = [
    "aiohttp>=3.11",
]

[project.urls]
Repository = "https://github.com/openremote/solyx-homeassistant-integration"
Issues = "https://github.com/openremote/solyx-homeassistant-integration/issues"
Source = "https://github.com/openremote/solyx-homeassistant-integration"

[tool.setuptools.packages.find]
where = ["."]
include = ["solyx_energy_api*"]

[tool.setuptools.package-data]
solyx_energy_api = ["py.typed"]
